import type { RelatedLink } from "@/components/GuideRelated";

export type PhaseThreeGuide = {
  path: string;
  title: string;
  description: string;
  h1: string;
  intro: string;
  categoryHref: string;
  categoryLabel: string;
  blurb: string;
  sections: Array<{ heading: string; paragraphs: string[] }>;
  related: RelatedLink[];
};

const commonRelated: RelatedLink[] = [
  { href: "/cnfans-size-guide", title: "CNFans UK Size Guide", blurb: "Measure and compare the fit before ordering." },
  { href: "/how-to-order", title: "How to Order", blurb: "A straightforward guide from browsing to tracking." },
  { href: "/cnfans-delivery-uk", title: "CNFans UK Delivery Guide", blurb: "UK timings, tracking and order updates." },
  { href: "/cnfans-finds", title: "CNFans Finds UK", blurb: "Explore clothing finds across the full edit." },
];

export const PHASE_THREE_GUIDES: PhaseThreeGuide[] = [
  {
    path: "/cnfans-t-shirt-finds", title: "CNFans T-Shirt Finds UK | Everyday Tees & Casual Tops",
    description: "Browse CNFans UK t-shirt finds, casual tops and everyday wardrobe pieces with simple sizing and styling notes for UK buyers.",
    h1: "CNFans T-Shirt Finds UK", categoryHref: "/category/tops", categoryLabel: "Browse T-Shirts & Tops",
    blurb: "Everyday tees, casual tops and useful notes on weight, fit and layering.",
    intro: "A dependable T-shirt earns its place by working with almost everything you own. This guide looks at everyday tees and casual tops through the details that matter in real life: fabric weight, neckline, length, ease through the body and how a tee sits under another layer.",
    sections: [
      { heading: "Start with the fabric weight", paragraphs: ["Light jersey feels cool and easy in warm weather, while a mid-weight cotton tee usually hangs more cleanly and keeps its shape through repeated wear. Heavier jersey gives a boxier outline and works well as the main part of an outfit, although it can feel warm beneath a sweatshirt. Think about when you will wear the tee most, then choose the weight around that.", "A smooth cotton surface creates a neater finish with trousers or an overshirt. A softer, slightly washed handle feels more casual with denim and relaxed bottoms. Neither needs to be saved for a particular occasion; the useful choice is the one that matches the rest of your week."] },
      { heading: "Choose a shape you will actually wear", paragraphs: ["Regular tees follow the body without clinging, relaxed cuts add room through the chest and sleeve, and boxy shapes are shorter with a wider line. Check shoulder position as well as chest width: a dropped shoulder changes the whole look even when the numerical measurement is similar.", "Length matters when you plan to leave a tee untucked. A hem around the hip is easy with jeans and cargos, while an overly long tee can bunch beneath a jacket. If you prefer a cleaner outfit, keep the body relaxed but make sure the sleeve and hem do not overwhelm your frame."] },
      { heading: "Build a useful colour rotation", paragraphs: ["White, black, grey and muted navy are easy foundations because they work across seasons. One or two neutral tees can support brighter outerwear, textured trousers or a matching set without competing for attention. Off-white often feels softer than bright white and pairs particularly well with stone, olive and washed denim.", "Colour is also affected by fabric. A washed black tee looks deliberately casual, while a deep solid black feels sharper. Look at the product images in daylight where possible and consider whether the shade needs to match something you already own."] },
      { heading: "Layer without adding bulk", paragraphs: ["A tee should sit smoothly beneath a hoodie, shirt or jacket. Lighter cotton is best when several layers are involved; a more substantial tee can replace the sweatshirt on mild days. Keep the neckline tidy if it will remain visible beneath an open shirt, and make sure the sleeve does not twist inside a close-fitting overshirt.", "For an uncomplicated outfit, combine a plain tee with relaxed trousers and one outer layer. The contrast can come from texture rather than a large graphic: jersey, denim and a woven jacket already give the look enough depth."] },
      { heading: "Care that keeps the neckline tidy", paragraphs: ["Cool washing, turning the tee inside out and avoiding excessive tumble-dryer heat will help the body and collar hold their shape. Reshape the neckline while damp and dry according to the care label. This matters most with cotton, which can change slightly after its first wash."] },
    ], related: commonRelated,
  },
  {
    path: "/cnfans-tracksuit-finds", title: "CNFans Tracksuit Finds UK | Co-ords, Sets & Casual Fits",
    description: "Explore CNFans UK tracksuit finds, matching sets and relaxed everyday outfits with simple style and size guidance.",
    h1: "CNFans Tracksuit Finds UK", categoryHref: "/category/co-ords-sets", categoryLabel: "Browse Tracksuits & Sets",
    blurb: "Matching tracksuits, relaxed sets and practical ways to wear each piece separately.",
    intro: "A tracksuit is useful well beyond quiet weekends. The right set gives you an easy complete outfit, yet the top and bottoms should also work separately with pieces already in your wardrobe. Here we focus on proportion, fabric, comfort and simple styling rather than a single fixed look.",
    sections: [
      { heading: "A set should work two ways", paragraphs: ["Begin by asking whether you would wear the jacket or sweatshirt without its matching bottoms. A useful set might pair a zip top with denim, or joggers with a plain tee and coat. That flexibility gives you more outfits and prevents the tracksuit feeling like something reserved for one setting.", "Matching colours create a clean uninterrupted line, while a set with small tonal differences feels more relaxed. If you often mix pieces, neutral black, charcoal, navy or stone will be easier to connect with the rest of your wardrobe."] },
      { heading: "Pick the fabric for the season", paragraphs: ["Brushed fleece holds warmth and suits colder days, though it can feel bulky under fitted outerwear. Loopback cotton is more breathable and works across spring, cool summer evenings and early autumn. Smooth jersey or technical woven fabric creates a lighter, sportier outline and dries more quickly after washing.", "Check whether the waistband, cuffs and hem have enough recovery to hold their shape. Softness is pleasant, but structure at these points stops a relaxed set looking tired after a few wears."] },
      { heading: "Balance the top and bottoms", paragraphs: ["An oversized sweatshirt looks most considered with joggers that taper or fall cleanly, rather than gathering heavily at the ankle. A shorter zip jacket can balance wider straight-leg bottoms. The aim is not to make everything slim; it is to let one part provide shape when the other has more volume.", "Look at both top and bottom measurements because sets do not always fit identically across the body. If your usual sizes differ, check whether the pieces are sold together and decide which measurement matters most for comfort."] },
      { heading: "Wear it beyond the matching look", paragraphs: ["Break up a tracksuit with familiar wardrobe pieces. The bottoms can sit with a crisp tee and overshirt, while the top works with jeans, cargos or simple trousers. A long coat over a plain set is an easy way to add structure in colder weather without losing comfort.", "Footwear changes the mood quickly. Clean low-profile trainers keep the outfit simple; a more substantial shoe balances wide or heavy joggers. Keep socks and base layers quiet when the set already carries the colour."] },
      { heading: "Comfort without careless fit", paragraphs: ["A relaxed tracksuit still needs a secure waistband, sensible rise and sleeves that finish near the wrist. Too much extra length creates bunching and makes movement less comfortable. Check the inside leg and body length against a set you already enjoy wearing.", "Follow the care label and wash matching pieces together so their colour ages at the same pace. Drying on lower heat also protects elastic and helps brushed fabrics retain their surface for longer." ] },
    ], related: commonRelated,
  },
  {
    path: "/cnfans-sweatshirt-finds", title: "CNFans Sweatshirt Finds UK | Everyday Sweatshirts & Layers",
    description: "Find CNFans UK sweatshirt picks for daily wear, layering and relaxed fits with practical notes for UK clothing buyers.",
    h1: "CNFans Sweatshirt Finds UK", categoryHref: "/category/tops", categoryLabel: "Browse Sweatshirts & Tops",
    blurb: "Crewnecks and relaxed layers chosen around fabric, shape and everyday use.",
    intro: "The best sweatshirt sits in the useful space between a T-shirt and a jacket. It is warm enough for a cool morning, easy beneath outerwear and relaxed without needing to look shapeless. This guide covers crewnecks, fabric weights, layering room and the details that make repeated wear comfortable.",
    sections: [
      { heading: "Crewneck shape makes the difference", paragraphs: ["A close but comfortable crewneck keeps its line beneath a coat and looks tidy over a tee. Wider neck openings feel more relaxed but can expose the base layer, so consider how you normally style yours. Ribbing should recover after it is stretched rather than sitting loose around the collar.", "Shoulder shape changes the mood. A set-in sleeve looks classic and neat, while a dropped shoulder gives a broader, easier outline. Choose based on your preferred proportion, not simply because one is described as oversized."] },
      { heading: "Brushed fleece or loopback", paragraphs: ["Brushed fleece has a soft, warm inner surface and is ideal when the sweatshirt will replace a light jacket. Loopback fabric feels cooler, breathes more easily and layers with less bulk. A dense outer face usually holds a cleaner shape than very thin jersey, especially around the chest and hem.", "For an all-season option, a medium-weight loopback or lightly brushed cotton is the most adaptable. It works alone in mild weather and leaves enough space beneath outerwear when temperatures drop."] },
      { heading: "Get the relaxed fit in proportion", paragraphs: ["Extra width through the body should be balanced by a hem that finishes in a useful place. If the sweatshirt is both very wide and very long, it can cover the shape of every pair of bottoms. A slightly shorter body with relaxed sleeves often feels more deliberate.", "Check sleeve length from the shoulder construction shown. Dropped seams add visual length even before the sleeve measurement begins. Cuffs can hold a little excess fabric, but too much bunching becomes awkward beneath a jacket."] },
      { heading: "Simple ways to layer it", paragraphs: ["Wear a crewneck over a plain tee and let only a narrow edge show at the collar or hem. Under a jacket, keep the sweatshirt smooth and avoid stuffing thick sleeves into narrow armholes. With a roomy coat, a heavier crewneck adds warmth without the hood bulk of a hoodie.", "On milder days, pair it with straight trousers or denim and treat it as the main layer. A tonal outfit of grey, navy or stone can look considered while remaining very easy to put together."] },
      { heading: "Keep ribbing and fabric in shape", paragraphs: ["Wash cooler and avoid hanging a heavy wet sweatshirt from the shoulders, which can stretch the body. Dry it flat or according to the label, and do not overheat elasticated cuffs. Turning it inside out also reduces rubbing across the visible surface.", "Small signs of wear are natural on brushed fabrics. Gentle washing and giving the sweatshirt a day between wears will help the fibres recover and keep it useful through more than one season." ] },
    ], related: commonRelated,
  },
  {
    path: "/cnfans-trouser-finds", title: "CNFans Trouser Finds UK | Casual Trousers & Everyday Bottoms",
    description: "Browse CNFans UK trouser finds, everyday bottoms and relaxed fits with simple sizing and styling guidance.",
    h1: "CNFans Trouser Finds UK", categoryHref: "/category/bottoms", categoryLabel: "Browse Trousers & Bottoms",
    blurb: "Casual trousers with clear notes on rise, leg shape, fabric and length.",
    intro: "Trousers set the proportion for the whole outfit, so a useful pair needs more than the right waist number. Rise, thigh room, leg shape, fabric and finished length all affect how they feel through a normal day. These notes are designed to make those choices easier before you order.",
    sections: [
      { heading: "Begin with rise and waist", paragraphs: ["A mid-rise is the most familiar choice for everyday wear, sitting securely without feeling especially high or low. Higher rises can lengthen the leg line and work well with shorter tops; lower rises feel more casual but may need extra care when choosing body length above them.", "Check whether the waist is fixed, elasticated or adjusted with a drawcord. An elastic waist offers flexibility, while a structured waistband gives a sharper line. Use the actual garment measurement and allow the ease you normally prefer."] },
      { heading: "Choose the leg shape deliberately", paragraphs: ["Straight legs are versatile and sit easily with most footwear. Tapered trousers provide room at the thigh before narrowing at the ankle, while wide legs create a stronger silhouette and need the length to be right. Relaxed should mean comfortable movement, not excess fabric everywhere.", "Look at front and side images to see where the cloth falls. Pleats add room near the hip and can improve drape, whereas a flat front stays simple beneath untucked tops."] },
      { heading: "Fabric changes the level of formality", paragraphs: ["Cotton twill feels sturdy and casual, making it useful with sweatshirts, tees and jackets. A smoother woven cloth creates a cleaner trouser that can sit with knitwear or an overshirt. Fabrics with a little stretch are comfortable for long days, but the cut should still provide most of the movement.", "For warmer months, lighter cloth and a little room through the leg improve airflow. In winter, denser twill or brushed fabric gives more substance and works with heavier footwear and outerwear."] },
      { heading: "Length and the break at the shoe", paragraphs: ["A clean hem that just meets the shoe is easy to wear and keeps a straight silhouette. A slight break feels relaxed, while heavy stacking can make trousers look shorter and untidy unless it is a deliberate part of the cut. Compare the listed inside leg with trousers you already own.", "If you alternate between trainers and boots, choose a length that works with the lower shoe first. A small turn-up can adjust casual trousers, but formal-looking cloth is usually better at its intended length."] },
      { heading: "Build outfits around proportion", paragraphs: ["Relaxed trousers pair well with a neater tee, sweatshirt or jacket, while a wider top can work when the trouser falls cleanly rather than bunching. Tucking or partially tucking a top reveals the waist and helps define longer, looser shapes.", "Start with colours that repeat easily: charcoal, navy, black, olive and stone. Texture and cut can provide interest without making the trousers difficult to combine with the rest of your wardrobe." ] },
    ], related: commonRelated,
  },
  {
    path: "/cnfans-cargo-pants-finds", title: "CNFans Cargo Pants Finds UK | Utility Bottoms & Streetwear Fits",
    description: "Explore CNFans UK cargo pants finds, utility bottoms and streetwear-inspired fits for everyday outfits.",
    h1: "CNFans Cargo Pants Finds UK", categoryHref: "/category/bottoms", categoryLabel: "Browse Cargo Pants & Bottoms",
    blurb: "Utility bottoms with practical advice on pockets, cloth, shape and styling.",
    intro: "Cargo pants combine useful storage with a relaxed shape, but pocket placement, fabric and leg width decide whether a pair feels balanced or unnecessarily bulky. This guide looks at everyday utility trousers that can move between a simple weekday outfit and a more layered casual look.",
    sections: [
      { heading: "Utility details should earn their place", paragraphs: ["Cargo pockets add weight and width at the thigh, so their position matters. Flat bellows pockets keep a cleaner line, while larger three-dimensional pockets create a stronger utility shape. Think about what you will actually carry: a secure phone pocket is useful, but too many heavy items can pull the trousers out of shape.", "Look for fastenings that are easy to use and stitching that lies neatly around each pocket. Drawcord hems, knee panels and extra tabs can be practical, although a quieter design will combine with more tops and jackets."] },
      { heading: "Choose cloth for movement and weather", paragraphs: ["Cotton twill has enough structure to support cargo pockets and softens naturally with wear. Ripstop is often lighter and more resistant to small tears, which suits travel and changeable weather. A smoother technical fabric creates a sharper, lighter pair, but may feel less substantial in winter.", "For year-round wear, medium-weight cloth is the sensible middle ground. It should bend comfortably at the knee without collapsing around the pockets or feeling stiff when you sit."] },
      { heading: "Control the volume through the leg", paragraphs: ["Relaxed cargos need room through the seat and thigh, but the lower leg can be straight, tapered or adjusted at the hem. A taper works with low trainers and prevents excess fabric gathering. Straight legs feel more current and sit well over a sturdier shoe, provided the inside leg is not too long.", "Balance wide cargos with a tee or sweatshirt that has a clear hem. If both halves are oversized, a shorter jacket or visible waistline can restore proportion without making the outfit fitted."] },
      { heading: "Build an easy cargo outfit", paragraphs: ["Start with a plain T-shirt, sweatshirt or knit and let the pockets provide the detail. Olive, black, charcoal and stone cargos work with most neutral tops; navy and brown offer a softer alternative. In colder weather, add a simple bomber, overshirt or coat rather than another heavily detailed layer.", "Keep care straightforward: empty every pocket, close fastenings and wash inside out according to the label. This protects pocket edges and prevents cords or tabs catching on other garments." ] },
    ], related: commonRelated,
  },
  {
    path: "/cnfans-jeans-finds", title: "CNFans Jeans Finds UK | Denim, Casual Fits & Everyday Styling",
    description: "Browse CNFans UK jeans finds, denim styles and casual bottoms with practical notes on fit, length and everyday styling.",
    h1: "CNFans Jeans Finds UK", categoryHref: "/category/bottoms", categoryLabel: "Browse Jeans & Bottoms",
    blurb: "Denim fits explained through rise, wash, leg shape and finished length.",
    intro: "Jeans are simple in theory and surprisingly personal in practice. The same waist can feel completely different when the rise, thigh and denim weight change. These notes help you compare everyday denim by shape, wash and length, with an emphasis on pairs that settle naturally into a weekly wardrobe.",
    sections: [
      { heading: "Fit starts above the knee", paragraphs: ["Waist size is only the beginning. Check the rise, seat and thigh before deciding between straight, relaxed or tapered denim. A comfortable thigh lets the leg fall properly; sizing up only to gain room there can leave the waistband too loose and change the intended shape.", "Mid-rise jeans are easy with most tops. A higher rise works well with shorter jackets and tucked tees, while a lower rise creates a looser casual line. Compare the front rise with jeans you already wear, not just the labelled size."] },
      { heading: "Understand denim weight and stretch", paragraphs: ["Rigid cotton denim begins firmer and develops its own creases and softness with use. Stretch denim feels comfortable immediately and can be useful for close cuts, although too much stretch may lose definition. Medium-weight denim offers the most adaptable balance for the UK climate.", "A heavy pair suits cool weather and structured outfits, while lighter denim is easier through spring and summer. Check care instructions because hot washing can alter both colour and fit."] },
      { heading: "Wash changes the mood", paragraphs: ["Dark indigo and clean black denim look sharper with knitwear, shirts and coats. Mid-blue is the everyday all-rounder, while pale or washed finishes feel more relaxed in brighter months. Fading around seams should look consistent with the rest of the finish rather than appearing as an isolated effect.", "If you want one pair to cover the most outfits, choose a restrained mid-blue or dark wash with limited distressing. It will sit as easily with a sweatshirt as it does with a neater jacket."] },
      { heading: "Get the hem right", paragraphs: ["Straight jeans can meet the shoe with a small break; wide jeans need enough length to hang properly without dragging. Tapered cuts usually look cleaner with less stacking at the ankle. Measure the inside leg of a pair that works with your usual footwear and compare it directly.", "Turn jeans inside out for washing, use cooler water and wash only when needed. This slows colour loss and reduces unnecessary stress on the denim while allowing the fabric to soften through normal wear." ] },
    ], related: commonRelated,
  },
  {
    path: "/cnfans-co-ord-finds", title: "CNFans Co-ord Finds UK | Matching Sets & Everyday Outfits",
    description: "Explore CNFans UK co-ord finds, matching sets and easy outfit combinations for casual everyday wear.",
    h1: "CNFans Co-ord Finds UK", categoryHref: "/category/co-ords-sets", categoryLabel: "Browse Co-ords & Sets",
    blurb: "Matching sets that work together and as useful separates throughout the week.",
    intro: "A co-ord removes the hardest part of getting dressed because colour, cloth and proportion have already been considered together. The best sets also avoid becoming one-outfit purchases: each half should make sense with the clothes you own and feel comfortable across a normal day.",
    sections: [
      { heading: "Look beyond the complete set", paragraphs: ["Before ordering, picture the top with your usual jeans or trousers and the bottoms with a plain tee or knit. If both combinations work, the set has real wardrobe value. Neutral colours are easy to split, while a distinctive colour can still work when one half is paired with black, navy or cream.", "Check whether the pieces are available in separate sizes. When they are sold together, compare both sets of measurements and prioritise the area where you need the most precise fit."] },
      { heading: "Match fabric to the occasion", paragraphs: ["Sweatshirt jersey and loopback cotton suit relaxed days, travel and easy layering. Knitted sets have a softer drape and can look neater with a coat. Woven shirt-and-trouser combinations feel light in warm weather, while structured twill gives a more defined silhouette.", "Texture keeps a single-colour outfit interesting. Ribbing, a visible weave or a brushed surface adds depth without requiring extra patterns or accessories."] },
      { heading: "Keep proportions balanced", paragraphs: ["A short or fitted top can balance wide-leg bottoms, while a relaxed sweatshirt works well with a straighter lower half. When both pieces are loose, the shoulder, waist or hem needs enough definition to prevent the set overwhelming your frame.", "Pay attention to top length when wearing the set beneath a jacket. A clean line between jacket and waistband makes the layers look intentional and keeps movement comfortable."] },
      { heading: "Style and care as one outfit", paragraphs: ["Simple footwear and one outer layer are usually enough because the matching cloth already pulls the look together. You can introduce contrast with a white tee beneath an open top, a darker coat or a different texture rather than another strong colour.", "Wash both pieces together whenever possible so colour and surface age evenly. Follow the more delicate care instruction if the top and bottom labels differ, and store knit sets folded to prevent stretching." ] },
    ], related: commonRelated,
  },
  {
    path: "/cnfans-streetwear-finds", title: "CNFans Streetwear Finds UK | Hoodies, Jackets, Sets & Bottoms",
    description: "Browse CNFans UK streetwear finds across hoodies, jackets, sets and bottoms with simple outfit ideas for UK buyers.",
    h1: "CNFans Streetwear Finds UK", categoryHref: "/category/new-in", categoryLabel: "Browse New Clothing Finds",
    blurb: "Relaxed hoodies, outerwear, sets and bottoms brought together with balanced proportions.",
    intro: "Streetwear is most useful when it fits into real everyday dressing rather than depending on one statement piece. A good rotation brings together relaxed tops, practical outerwear and comfortable bottoms, then uses proportion and texture to make the outfit feel considered.",
    sections: [
      { heading: "Build from dependable layers", paragraphs: ["Start with a tee, sweatshirt or hoodie that fits comfortably beneath outerwear. Add a jacket with enough room at the shoulder and sleeve, then choose bottoms that balance the volume above. This simple sequence works whether the pieces are tonal or carry more colour.", "A wardrobe built around layers handles British weather better than one based on complete fixed outfits. You can remove the jacket indoors, add a coat in winter or use the same base layer through a mild summer evening."] },
      { heading: "Use proportion rather than excess", paragraphs: ["Relaxed does not require every garment to be extremely oversized. A boxy hoodie can sit with straight jeans; wide cargos work with a cleaner tee; a broad jacket benefits from trousers that fall without heavy bunching. One clear shape is often stronger than several competing ones.", "Check shoulder width, body length and inside leg rather than choosing a larger label for the sake of volume. Purposeful room should still allow cuffs, hems and waistbands to sit where intended."] },
      { heading: "Texture makes neutral outfits work", paragraphs: ["Black, grey, olive, navy and stone become more interesting when jersey, denim, twill and padded outerwear appear together. This is a reliable way to create depth without relying on loud wording or difficult colour combinations.", "If you introduce one brighter piece, repeat a smaller part of its tone elsewhere or keep everything around it calm. The aim is an outfit you can wear again, not just one that catches attention once."] },
      { heading: "Dress for the day ahead", paragraphs: ["Pockets, adjustable hems and weather-suitable fabric matter when you are travelling or outdoors. For an ordinary day, comfort at the waist and enough movement through the shoulder will matter more than extra decoration. Choose details that solve a real need.", "Care for each fabric separately even when pieces form one outfit. Denim, fleece and coated outerwear rarely need the same wash, so follow individual labels and allow jackets to air between wears." ] },
    ], related: commonRelated,
  },
  {
    path: "/cnfans-winter-jacket-finds", title: "CNFans Winter Jacket Finds UK | Outerwear, Coats & Layering",
    description: "Explore CNFans UK winter jacket finds, outerwear and layering pieces for colder UK weather and everyday outfits.",
    h1: "CNFans Winter Jacket Finds UK", categoryHref: "/category/outerwear", categoryLabel: "Browse Winter Outerwear",
    blurb: "Cold-weather jackets considered through warmth, weather, layering room and daily use.",
    intro: "A winter jacket for the UK needs to manage more than low temperature. Wind, damp mornings, warm public transport and frequent changes between indoors and outside all matter. This guide focuses on sensible insulation, useful coverage and enough space for layers without unnecessary bulk.",
    sections: [
      { heading: "Choose warmth for your routine", paragraphs: ["A heavily insulated jacket suits long periods outdoors, but can feel excessive on a commute built around trains, buses and heated buildings. Lighter insulation with a sweatshirt or knit underneath offers more control. Think about the coldest part of your normal day rather than buying only for an occasional extreme.", "Length affects warmth as much as filling. A jacket covering the hip protects more of the body, while a shorter cut is easier for driving and active movement."] },
      { heading: "Plan the layers underneath", paragraphs: ["Measure a jacket over the sort of top you will actually wear in winter. Shoulder room, armhole depth and sleeve width need to accommodate a knit or hoodie without pulling. Simply sizing up can make the body too long, so use garment measurements wherever possible.", "A smooth lining helps layers move without catching. Adjustable cuffs and a secure neck closure reduce draughts and can make moderate insulation feel much warmer."] },
      { heading: "Weather details that matter", paragraphs: ["A shower-resistant outer is useful for changeable days, though it is not the same as a fully waterproof coat. Hoods, storm flaps and covered zips add protection when you are caught outside. Secure internal pockets keep essentials away from the weather.", "Dark neutrals disguise everyday marks, while stone, olive and muted colours brighten a winter wardrobe without becoming difficult to style. Check the care label before assuming a padded or coated jacket can go into a standard wash."] },
      { heading: "Balance warmth with everyday style", paragraphs: ["Puffer jackets work with straight denim, cargos and casual trousers; longer coats create a cleaner line over sweatshirts or matching sets. Keep bulky layers in proportion by choosing bottoms that fall clearly to the shoe rather than gathering heavily.", "Air outerwear after damp journeys and allow it to dry fully before storage. At the end of the season, clean it according to the label and store it with enough space to protect the filling and shape." ] },
    ], related: commonRelated,
  },
  {
    path: "/cnfans-summer-outfits", title: "CNFans Summer Outfits UK | T-Shirts, Shorts & Light Layers",
    description: "Browse CNFans UK summer outfit ideas, including t-shirts, light layers and easy casual pieces for warmer days.",
    h1: "CNFans Summer Outfits UK", categoryHref: "/category/tops", categoryLabel: "Browse Summer Tops",
    blurb: "Breathable tees, light bottoms and easy layers for warmer British days.",
    intro: "British summer dressing needs to cover warm afternoons, cooler evenings and the occasional shower in the same outfit. Breathable fabric and uncomplicated layers are more useful than buying only for the hottest day. These ideas keep comfort, proportion and repeat wear at the centre.",
    sections: [
      { heading: "Begin with breathable foundations", paragraphs: ["Cotton jersey, light woven fabric and relaxed shapes allow air to move without making an outfit look oversized. A mid-weight tee often hangs better than very thin cloth and remains useful beneath a layer. For bottoms, leave enough room through the thigh and avoid a waistband that feels tight when sitting.", "Pale neutrals, washed blues, olive and soft grey reflect the season without requiring an entirely separate wardrobe. Dark colours still work when the cloth is light and the fit is easy."] },
      { heading: "Shorts need the right length", paragraphs: ["Choose shorts around rise, thigh room and finished length rather than a trend-led number. A hem around the middle of the thigh feels casual; a slightly longer cut provides more coverage and balances a loose tee. The leg opening should allow movement without flaring excessively.", "Cotton twill feels structured, jersey is relaxed and light woven fabric suits hotter days. Secure pockets are valuable for travel and everyday errands."] },
      { heading: "Keep one light layer nearby", paragraphs: ["An overshirt, fine sweatshirt or unlined jacket handles evening temperature changes and air-conditioned spaces. It should fold easily and sit over a tee without pulling at the shoulder. Open fronts create a vertical line that can make relaxed summer pieces feel tidier.", "If rain is likely, choose a light shower-resistant shell rather than carrying a heavy winter jacket. The layer can provide the stronger colour while the base outfit stays simple."] },
      { heading: "Make a small summer rotation", paragraphs: ["Two or three tees, one light shirt, comfortable shorts and a pair of airy trousers can create plenty of combinations. Repeating colours across the group means almost every top works with every bottom, which is especially useful when packing.", "Wash lighter fabrics gently and avoid excessive heat, which can affect cotton length and elastic waistbands. Let pieces dry fully before folding and follow the individual care label." ] },
    ], related: commonRelated,
  },
  {
    path: "/cnfans-men-clothing-finds", title: "CNFans Men’s Clothing Finds UK | Everyday Menswear & Casual Fits",
    description: "Explore CNFans UK men’s clothing finds, including tops, trousers, jackets and casual outfit ideas for everyday wear.",
    h1: "CNFans Men’s Clothing Finds UK", categoryHref: "/category/new-in", categoryLabel: "Browse Men's Clothing Finds",
    blurb: "Everyday menswear built around useful tops, trousers, jackets and repeatable outfits.",
    intro: "A useful menswear wardrobe is less about owning more and more about choosing pieces that connect. Comfortable trousers, dependable tops and one or two layers can cover most ordinary weeks when the colours, fabrics and proportions work together.",
    sections: [
      { heading: "Build a dependable base", paragraphs: ["Start with tops you can wear alone and beneath a jacket: plain tees, a sweatshirt or knit, and perhaps an easy overshirt. Add straight or relaxed trousers in a neutral colour. These pieces become the reference point for every later purchase, making it easier to judge whether something new will earn regular wear.", "Quality is felt in practical details such as a stable neckline, secure waistband and cloth that suits the intended season. Look past the first product image and check measurements, fabric notes and care information."] },
      { heading: "Use fit to create variety", paragraphs: ["You do not need a different colour for every outfit. A regular tee, relaxed sweatshirt and boxier jacket can all feel distinct in the same palette because their shapes change the proportion. Straight trousers are versatile; a wider or tapered pair adds another option without replacing them.", "Keep one area defined when wearing volume elsewhere. A clean shoulder, visible waistband or trouser hem that meets the shoe properly can make casual clothing feel deliberate."] },
      { heading: "Add layers for the UK climate", paragraphs: ["An overshirt or light jacket covers much of spring and autumn, while a roomy winter coat should leave space for knitwear. In summer, a breathable shirt or fine sweatshirt is useful after sunset. Choosing layers with different weights makes the same base outfit work across more months.", "Consider pockets, closures and weather resistance based on your actual commute and weekends. Practical details are valuable when they make the garment easier to use, not simply because there are more of them."] },
      { heading: "Keep outfits easy to repeat", paragraphs: ["A simple colour group such as navy, grey, stone and black removes much of the guesswork. Denim and olive can act almost like neutrals, while one stronger seasonal colour brings variation. Repeat an outfit with different footwear or outerwear rather than feeling every combination must be entirely new.", "Care extends that rotation. Wash only as needed, separate fabrics by their instructions and give jackets time to air. Clothing that retains its shape is easier to rely on week after week." ] },
    ], related: commonRelated,
  },
  {
    path: "/cnfans-uk-new-in", title: "CNFans UK New In | Latest Clothing Finds & Everyday Styles",
    description: "Browse CNFans UK new clothing finds, recent styles and everyday apparel picks across tops, bottoms, jackets and sets.",
    h1: "CNFans UK New In", categoryHref: "/category/new-in", categoryLabel: "Browse New In",
    blurb: "Recent clothing arrivals considered for fit, season and everyday wardrobe value.",
    intro: "New arrivals are easiest to shop when you know what is missing from your wardrobe. Rather than treating every recent style as a must-have, this guide helps you compare fresh tops, bottoms, jackets and sets by fit, season and how naturally they work with clothes you already wear.",
    sections: [
      { heading: "Shop newness with a purpose", paragraphs: ["Take a quick look at your regular week before browsing. You may need another light top for layering, trousers with a different shape or outerwear for a change in weather. A clear gap gives you a better filter than simply choosing the newest colour or silhouette.", "Recent arrivals can also refresh existing outfits. One well-chosen jacket or pair of bottoms often changes more combinations than several tops that all serve the same role."] },
      { heading: "Check the season, not only the date", paragraphs: ["A new piece is most useful when its fabric matches the months ahead. Loopback sweatshirts and light jackets bridge seasons, breathable tees and woven tops suit warmer weather, and denser outerwear earns its place as temperatures fall. UK weather makes adaptable layers especially valuable.", "Colour can move between seasons too. Stone, navy, olive, grey and washed blue connect easily with an existing wardrobe and remain wearable after a short trend has passed."] },
      { heading: "Compare fit across categories", paragraphs: ["A relaxed top may need straighter bottoms for balance, while wide trousers work well with a shorter or more defined layer. When considering several new pieces, picture them as one small group and check that their proportions cooperate rather than competing.", "Read measurements each time, even if you have ordered a similar category before. Different cuts are designed with different ease, and the intended shape matters as much as the size label."] },
      { heading: "Give recent finds lasting value", paragraphs: ["Ask whether you can name three realistic ways to wear a piece. A jacket might sit over a tee, sweatshirt and matching set; trousers might work with trainers, boots and several top weights. That quick test separates useful variety from duplication.", "Availability can change as batches move, so confirm size and colour when you are ready. Once the item arrives, follow its care label from the first wash to protect the fabric and intended fit." ] },
    ], related: commonRelated,
  },
];

export function getPhaseThreeGuide(path: string) {
  const guide = PHASE_THREE_GUIDES.find((item) => item.path === path);
  if (!guide) throw new Error(`Missing phase three guide configuration for ${path}`);
  return guide;
}
